### ISSUE TITLE
restmail.net is down / ERR_SSL_VERSION_OR_CIPHER_MISMATCH

### ISSUE THREAD

**Issue by kmarek** [mozilla/restmail.net#171]
Site restmail.net is down 

This site can't provide a secure connection / restmail.net uses an unsupported protocol
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

![image](https://github.com/user-attachments/assets/9e6605ea-ab2b-4029-a796-305a7fa1cc11)

https://www.webpagetest.org/result/241022_AiDc6B_9PY/

Last time it was working was about 2 hours ago (5pm 22 OCT 2024 UTC)

**Comment by GaganUppaldev** [comment]
I believe this error might be caused by a CORS issue. Could you please provide a code snippet or guidance to resolve it?
