### ISSUE TITLE
limit uses of restmail.net

### ISSUE THREAD

**Issue by jrgm** [mozilla/restmail.net#28]
1) if you send a bulk list longer than N, we flat out reject
 2) domain MUST be on a whitelist of domains ([restmail.net] to start).

/cc @stephendonner

**Comment by jrgm** [comment]
@stephendonner

Would a policy like I outlined above break any of your testing, or any other restmail.net consumers within mozilla, or outside, that you know about.

**Comment by jrgm** [comment]
Also whitelist restmail.com, and case insensitive, of course.

**Comment by jrgm** [comment]
Small note: changes for this will have to run on node4, at least in the short term.

**Comment by rfk** [comment]
Looks like this repo isn't connected to our waffle, and I don't have admin rights to connect it - @jrgm are you able to tweak the owners of this repo to include fxa-admins or similar?

**Comment by jrgm** [comment]
> Looks like this repo isn't connected to our waffle, and I don't have admin rights to connect it - @jrgm are you able to tweak the owners of this repo to include fxa-admins or similar?

This admin of this repo is now @mozilla/fxa-core

**Comment by jrgm** [comment]
fixed in https://github.com/mozilla/restmail.net/pull/33
